
spring:
  application:
    name: spring-config-server

  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zhengfuwei/SpringcloudConfig
          search-paths: src/respo
          username:
          password:

server:
  port: 8888
